import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home({ data }) {

  const recipes = data.recipes
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Recipe App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next Recipe App</h1>
        <Link href="/">
          <a>{recipes[0].title}</a>
        </Link>

        <p className={styles.description}>
          The app that is always right next to you
        </p>
      </main>

      <footer className={styles.footer}>
        <p>Powered by Mari Savoldi</p>
      </footer>
    </div>
  )
}

export function getStaticProps() {
  return {
    props: {
      data: {
        recipes: [{ "title": "Pineapple Smoothie" }]
      }
    }
  }
}